name: Welcome Greetings

on:
  issues:
    types:
      - opened
  pull_request:
    branches:
      - main
    types:
      - opened
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  greetings:
    name: Welcome New Contributors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/first-interaction@v3.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

          issue_message: |
            ## ğŸ‘‹ Hello there, and welcome!

            Thank you for opening an issue â€” we're happy to have you here! ğŸ‰
            Before we move forward, please take a moment to review the following:

            - ğŸ“˜ **[Code of Conduct]**
            - ğŸ› ï¸ **[Contribution Guidelines]**

            These help keep our community healthy and ensure smooth collaboration for everyone.
            We appreciate your time and effort â€” thanks for helping improve the project! ğŸ™Œ

            [Code of Conduct]: https://github.com/homelab-alpha/adguard-home/blob/main/CODE_OF_CONDUCT.md
            [Contribution Guidelines]: https://github.com/homelab-alpha/adguard-home/blob/main/CONTRIBUTING.md

          pr_message: |
            ## ğŸ‘‹ Hello, and thank you for your contribution! ğŸ‰

            We appreciate your pull request â€” your support helps the project grow! ğŸš€
            Our team will review your submission as soon as possible.

            In the meantime, please ensure the following:

            - âœ… All relevant documentation is updated
            - âœ… All necessary tests are included and passing
            - âœ… CI/CD workflows complete successfully

            Thank you again for your time and effort. Weâ€™re looking forward to reviewing your pull request! ğŸ™Œ
